// Generated by CoffeeScript 1.3.1
(function() {

  jot.client.register({
    onInit: function($slides) {
      var i;
      i = 0;
      return $slides.each(function() {
        return this.id = "s" + (i++);
      });
    },
    onChange: function(position, onComplete) {
      var slide;
      slide = "#s" + position;
      $.scrollTo(slide, 1000, {
        easing: "swing",
        onAfter: onComplete
      });
      return console.log(slide);
    }
  });

}).call(this);
