// Generated by CoffeeScript 1.3.1
(function() {
  var client, jot;

  jot = client = {
    init: function(transition) {
      var $slides, count, current;
      $slides = $('hr');
      count = $slides.length;
      current = 0;
      $slides.css({
        "margin-top": "500px",
        "height": 0,
        "width": 0,
        "margin-left": "-9999px"
      });
      $($slides[0]).css({
        "margin-top": "0"
      });
      if (transition.onInit) {
        transition.onInit($slides);
      }
      return $(window).keydown(function(e) {
        console.log(current);
        switch (e.keyCode) {
          case 13:
          case 39:
            current = (current + 1) % count;
            break;
          case 37:
            if (current <= 0) {
              return;
            }
            current = (current - 1) % count;
            break;
          default:
            return;
        }
        if (transition.onChange) {
          return transition.onChange(current, function() {
            return window.location = "#s" + current;
          });
        }
      });
    },
    register: function(transition) {
      return $(function() {
        return jot.client.init(transition);
      });
    }
  };

}).call(this);
